services:
  node_service:
    image: node:latest
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "npm install express --save && npm run start"
    ports:
      - 3000:3000
  apache:
    build:
      context: .
      dockerfile: ./httpd.dockerfile
    ports:
      - 8001:80

  nginx:
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    ports:
      - 8000:80